name: fitbody
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.1
  cloudinary: ^1.2.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.2.0
  intro_slider: ^4.2.5
  numeric_selector: ^0.0.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/w1.png
    - assets/images/w12.png
    - assets/images/w2.png
    - assets/images/g1.png
    - assets/images/w3.png
    - assets/images/g2.png
    - assets/images/w4.png
    - assets/images/g3.png
    - assets/images/s1.png
    - assets/images/workout.png
    - assets/images/feed.png
    - assets/images/community.png
    - assets/images/track.png
    - assets/images/workout1.png
    - assets/images/feed1.png
    - assets/images/community1.png
    - assets/images/track1.png
    - assets/images/r1.png
    - assets/images/r2.png
    - assets/images/wc.png

flutter_native_splash:
  color: "#232323"
  image: assets/images/logo.png
  android: true
  ios: true
